// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Shifter
{
    internal sealed partial class Vsix
    {
        public const string Id = "Shifter.2788249e-f649-4ef6-a0e4-e390ccdbe588";
        public const string Name = "Shifter";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
