// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Shifter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ShifterString = "a3dc2100-ffab-436a-a3d6-96b5be081484";
        public static Guid Shifter = new Guid(ShifterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShiftDown = 0x0100;
        public const int ShiftUp = 0x0200;
        public const int IncrementalShiftDown = 0x0300;
        public const int IncrementalShiftUp = 0x0400;
    }
}